services:
  app-db:
    container_name: app-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:16
    profiles:
      - dev
      - prod
    ports:
      - "5432:5432"
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    networks:
      - common_tools_network

networks:
  common_tools_network:
    driver: bridge
    name: common_tools_network

volumes:
  app_pg_data: {}